### ISSUE TITLE
HumbleBundle - Export button doesn't show up on the library page

### ISSUE THREAD

**Issue by Aceridus** [ssokolow/itad_importer#16]
Great job on this script, it worked nicely on GOG!

When I went to my library page on Humble Bundle the 'Export to ITAD' button didn't show up anywhere.  After a bit of digging I suspected that the recent change to using a MutationObserver might be causing the issue, which appears to be the case.

The MutationObserver creates an interesting race condition based on page load times and connection speeds.  I happen to be on a really fast connection (Verizon FIOS) and I am guessing that the MutationObserver gets registered after the desired element has already been added to the page, so the desired mutation won't ever be observed.  On slower machines and/or connections it probably works fine because the MutationObserver is registered before the desired page element appears.

I made the following modification to the script, in Tampermonkey, at line 304:
```javascript
        topControls = document.querySelector('.top-controls');
        if (topControls) {
            console.log(".top-controls already exists, attach immediately.");
            button.appendTo(topControls);
        } else {
            observer = new MutationObserver(function(mutations) {
                return mutations.forEach(function(mutation) {
                    var found, tnode_cls;
                    tnode_cls = mutation.target.getAttribute("class");
                    console.log(mutation);
                    found = $(".top-controls", mutation.target);
                    if (found.length > 0) {
                        observer.disconnect();
                        return button.appendTo(found);
                    }
                });
            });
            observer.observe(document.querySelector('.top-controls'), config);
        }
```
The 'Export to ITAD' button is now appearing and working correctly for me.

I thought I would let you know, so you can integrate my change or a more desirable one based on what I realized!

**Comment by ssokolow** [comment]
That makes perfect sense. Something about my connection *does* make Humble page loads sluggish.

I'll adjust the script later today once I finish clearing out more urgent obligations.

**Comment by ssokolow** [comment]
Things are taking far longer than expected and I'll have to push the update tomorrow. Sorry.

**Comment by ssokolow** [comment]
There you go. I can't test the "page loads too quickly" case but the CoffeeScript I wrote should be a direct equivalent for the JavaScript you wrote.

**Comment by Aceridus** [comment]
Looks good on my end! The button is appearing as expected with your updated script.
