### ISSUE TITLE
'Quest for Glory 1-5' bundle not properly recognized on GOG.com

### ISSUE THREAD

**Issue by flamanar** [ssokolow/itad_importer#17]
Just reporting that itad_importer never picks up 'Quest for Glory 4' from the 'Quest for Glory 1-5' bundle on GOG.com. It will pick up games 1,2,3, and 5...and also adds an entry of "Quest for Glory 1-5".  Just a heads-up. thanks!

![itaperror](https://cloud.githubusercontent.com/assets/13957552/9569955/c52dcf72-4f49-11e5-96a2-127838de8901.jpg)

issue #11

**Comment by Shi9k** [comment]
The exact same thing seems to happen with Geneforge. Also 5 games, the fourth one doesn't show and there is a Geneforge 1-5 title

![screenshot-isthereanydeal com 2015-09-11 00-47-20](https://cloud.githubusercontent.com/assets/7720037/9806815/3e309326-5820-11e5-8c29-5a9af97ab5d0.png)
![screenshot-isthereanydeal com 2015-09-11 00-48-23](https://cloud.githubusercontent.com/assets/7720037/9806816/423e516a-5820-11e5-972e-0b279616a67b.png)

**Comment by ssokolow** [comment]
Interesting symptom. Thanks for pointing it out.

(And to everyone, my apologies for not getting to this sooner. It's been a messy couple of weeks. I'll try to get it debugged and pinned down to either my fault or ITAD's fault within the next 48 hours.)

**Comment by ssokolow** [comment]
Ok, I've confirmed that it's not a problem on my end. All entries are properly converted into JSON and submitted and, in both cases, the fourth entry in the series is identical to the others except for the number.

Please report this as a bug in IsThereAnyDeal.com itself via https://bitbucket.org/tfedor/isthereanydeal.com/issues and include a link to this page to ensure all gathered information is available for consideration.

Sorry for taking so long.
