### ISSUE TITLE
Game title is incorrect for new GOG games

### ISSUE THREAD

**Issue by xThrodx** [ssokolow/itad_importer#19]
When I import my GOG collection, the script assumes the text "new" next to the new games is part of the game title.

For example the game "Tyrian 2000" here:
![gog](https://cloud.githubusercontent.com/assets/14939634/10245873/2a8c73b0-690c-11e5-9b83-200777690f5f.png)

is imported as "TYRIAN 2000new"
![import](https://cloud.githubusercontent.com/assets/14939634/10245874/2a8e8e3e-690c-11e5-8d4c-8c22b91812b7.png)

**Comment by ssokolow** [comment]
Ugh. That'll be a major pain to fix. I have no easy way to trigger "new" badges so I can write proper "omit badge" code.

(I own no new games at the momet, I already own all of the cheap games I want, and my budget doesn't lend itself to buying games for testing purposes.)

Next time you've got "new" badges, could you save a copy of the page and send it to me so I can see the HTML involved?

(And, in the mean time, you can work around this by ridding yourself of the "new" badges. They're very ephemeral, so all it should take is clicking on all "new" entries at least once, then reloading the page.)

**Comment by JeremyMorton** [comment]
```HTML
<div class="product-row__title"><!-- ngIf: !product.isComingSoon && !product.isNew --><!-- ngIf: product.isComingSoon || product.isNew --><div class="product-title product-title--flagged" ng-if="product.isComingSoon || product.isNew" gog-labeled-title="{
                &quot;maxLineNumber&quot;: 2,
                &quot;title&quot;: &quot;AN ELDER SCROLLS LEGEND: BATTLESPIRE&quot;
             }"><span class="product-title__text" ng-bind="::product.title | uppercase">AN ELDER SCROLLS LEGEND: BATTLESPIRE</span><span class="product-title__flags"><!-- ngIf: product.isComingSoon --><!-- ngIf: product.isNew --><span ng-if="product.isNew" class="_product-flag product-title__flag">new</span><!-- end ngIf: product.isNew --></span></div><!-- end ngIf: product.isComingSoon || product.isNew --></div>
```

**Comment by ssokolow** [comment]
There you go.
