### ISSUE TITLE
HumbleBundle has changed format

### ISSUE THREAD

**Issue by Hallikas** [ssokolow/itad_importer#20]
HumbleBundle has changed page layout. It seems that script does not work with new layout at all.

**Comment by ssokolow** [comment]
Can you clarify? I just tested both the Humble Library view and the purchase pages and, aside from the known "sometimes you have to reload to get the button to appear" bug on the library view, it appears to be working fine.

(There seems to be some kind of race condition in how the script hooks the Humble Library view but I haven't been able to spend enough time on it to figure out where it's coming from.)

**Comment by Hallikas** [comment]
My mistake. Closing my browser and reopening humble library did helped. I was just too fast and thought that layout changes on Humble Bundle did something.
So, script works just fine, thanks for it.
