### ISSUE TITLE
Import of new games on GOG with long names creates unknown games in ITAD

### ISSUE THREAD

**Issue by lpmastor** [ssokolow/itad_importer#22]
So this is a super specific bug, but I've run into it a couple time so I wanted to report it.

In the GOG account library, if I look at games in GRID view (as opposed to LIST view), games with long names will occasionally get truncated if they are marked as "new". This truncated name can then get imported in ITAD.

Here's an example:
I recently bought "Star Trek: Starfleet Command Gold Edition" on GOG. When I import this game from the Order Confirmation page or from the library LIST view, there is no problem.
However, if I look at my games in GRID view and the "new" indicator is still visible, then the title gets truncated to "Star Trek: Starfleet Command Gold..." with the "NEW" indicator after it. If I import it using the importer, it creates an entry in ITAD with the truncated name.

If you want to see the differences in ITAD, the correct entry can be seen at
https://isthereanydeal.com/collection/#/page:game/info?plain=startrekstarfleetcommandgoldedition 

And the incorrect entry is located at
https://isthereanydeal.com/collection/#/page:game/info?plain=startrekstarfleetcommandgold

This issue can be worked around in GRID view: If you click on the game to display the game details and then refresh GRID view, the "new" indicator will go away and even though the name is still truncated, the right name does get imported into ITAD.

**Comment by ssokolow** [comment]
I'm already submitting everything I can scrape without firing off an extra HTTP request per game and the title should only be used when the GOG product ID doesn't match anything, so this is a problem on ITAD's end.

You'll want to report it on the [ITAD issue tracker](https://bitbucket.org/tfedor/isthereanydeal.com/issues) instead.
